In [2]:
import numpy as np

In [2]:
mylist=[1,2,3,4,5,6]

In [3]:
my_array1=np.array(mylist)

In [4]:
my_array1

array([1, 2, 3, 4, 5, 6])

In [5]:
mylist2=[7,8,9,10,11,12]

In [7]:
my_array2=np.array(mylist2)

In [8]:
my_array2

array([ 7,  8,  9, 10, 11, 12])

In [12]:
mylist=[mylist,mylist2]

In [13]:
final_array=np.array(mylist)

In [14]:
final_array


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
mylist.append(mylist2)

In [21]:
final_array.dtype

dtype('int32')

In [22]:
final_array.shape

(2, 6)

In [29]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
np.eye(1)

array([[1.]])

In [32]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [33]:
5/2

2.5

In [34]:
5//2

2

In [36]:
arr4=np.array([[111,222,333],[444,555,666]])

In [37]:
arr4

array([[111, 222, 333],
       [444, 555, 666]])

In [38]:
arr4*arr4

array([[ 12321,  49284, 110889],
       [197136, 308025, 443556]])

In [39]:
1/arr4

array([[0.00900901, 0.0045045 , 0.003003  ],
       [0.00225225, 0.0018018 , 0.0015015 ]])

In [40]:
arr4

array([[111, 222, 333],
       [444, 555, 666]])

In [41]:
arr4-arr4

array([[0, 0, 0],
       [0, 0, 0]])

In [42]:
arr4 **3

array([[  1367631,  10941048,  36926037],
       [ 87528384, 170953875, 295408296]], dtype=int32)

In [43]:
arr5=np.arange(0,100,5)

In [44]:
arr5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [45]:
arr5[0:8]

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [46]:
arr5[0:2]

array([0, 5])

In [49]:
slice_of_array=arr5[0:4]

In [50]:
slice_of_array

array([ 0,  5, 10, 15])

In [51]:
slice_of_array[:]=1

In [52]:
slice_of_array

array([1, 1, 1, 1])

In [53]:
i=10
slice_of_array[:]=i
i=i+7


In [54]:
slice_of_array

array([10, 10, 10, 10])

In [55]:
i

17

In [56]:
arr2d=np.array(([5,10,15],[7,14,21],[8,16,24]))

In [57]:
arr2d

array([[ 5, 10, 15],
       [ 7, 14, 21],
       [ 8, 16, 24]])

In [58]:
arr2d[1]

array([ 7, 14, 21])

In [59]:
arr2d[2][2]

24

In [60]:
arr2d[:1,1:]

array([[10, 15]])

In [66]:
arr2d[:1,1:]

array([[10, 15]])

In [65]:
arr2d[:2,1:]

array([[10, 15],
       [14, 21]])

In [82]:
arr_length=arr2d.shape[1]

In [83]:
arr_length

3

In [88]:
for i in range (arr_length):
    arr2d[i]=i+10

In [90]:
arr2d

array([[10, 10, 10],
       [11, 11, 11],
       [12, 12, 12]])

In [92]:
arr2d[[1,2]]

array([[11, 11, 11],
       [12, 12, 12]])

In [94]:
arr6=np.arange(50).reshape((10,5))

In [95]:
arr6

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [97]:
arr6.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [101]:
np.dot(arr6.T,arr6)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [3]:
arr7=np.arange(11)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr7)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.square(arr7)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [11]:
np.sort(arr7)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
a=np.random.randn(10)

In [23]:
b=np.random.randn(10)

In [19]:
np.add(a,b)

array([ 1.67600931,  0.3904034 ,  0.53353663,  1.44573911,  0.71321958,
       -1.05230669, -1.83710904, -1.18557637,  1.09963902,  1.78891368])

In [20]:
np.sqrt(a,b)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.13375517, 0.42813281, 0.50940403, 1.29553141,        nan,
              nan,        nan,        nan,        nan, 0.96017855])

In [25]:
np.maximum(a,b)

array([ 1.43526131, -0.06325975,  0.21466665,  0.5731702 ,  1.62385343,
       -0.62675367, -1.19766615,  2.69472357,  0.81803975, -0.52043978])

In [27]:
import webbrowser
website='google.com'
webbrowser.open(website)

True