# MERGE

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
dframe1=DataFrame({'key':['A','B','X','D','G'],'dataset':range(5)})
dframe1

key  dataset
0   A        0
1   B        1
2   X        2
3   D        3
4   G        4

In [3]:
dframe2=DataFrame({'key':['B','A','M','R','T'],'dataset':np.random.randn(5)})
dframe2

key   dataset
0   B -1.781601
1   A  1.288842
2   M -0.130184
3   R -0.397044
4   T  0.224469

In [8]:
pd.merge(dframe1,dframe2,on='key',how='outer',suffixes=['_1','_2'])

key  dataset_1  dataset_2
0   A        0.0  -0.291857
1   B        1.0   0.190620
2   X        2.0        NaN
3   D        3.0        NaN
4   G        4.0        NaN
5   M        NaN   0.589566
6   R        NaN  -0.411509
7   T        NaN   0.675618

In [9]:
pd.merge(dframe1,dframe2,on='key',how='left',suffixes=['_1','_2'])

key  dataset_1  dataset_2
0   A          0  -0.291857
1   B          1   0.190620
2   X          2        NaN
3   D          3        NaN
4   G          4        NaN

In [10]:
pd.merge(dframe1,dframe2,on='key',how='right',suffixes=['_1','_2'])

key  dataset_1  dataset_2
0   A        0.0  -0.291857
1   B        1.0   0.190620
2   M        NaN   0.589566
3   R        NaN  -0.411509
4   T        NaN   0.675618

In [16]:
dframe3=DataFrame({'key':['AA','BB','CC','DD','EE','FF'],'dframe3':[1,2,3,4,5,6]})
dframe3

key  dframe3
0  AA        1
1  BB        2
2  CC        3
3  DD        4
4  EE        5
5  FF        6

In [18]:
dframe4=DataFrame({'key':['AA','GG','TC','FD','EE','FF'],'dframe4':[1,6,35,46,57,66]})
dframe4

key  dframe4
0  AA        1
1  GG        6
2  TC       35
3  FD       46
4  EE       57
5  FF       66

In [19]:
pd.merge(dframe3,dframe4)

key  dframe3  dframe4
0  AA        1        1
1  EE        5       57
2  FF        6       66

In [24]:
pd.merge(dframe3,dframe4,on='key',how='outer')

key  dframe3  dframe4
0  AA      1.0      1.0
1  BB      2.0      NaN
2  CC      3.0      NaN
3  DD      4.0      NaN
4  EE      5.0     57.0
5  FF      6.0     66.0
6  GG      NaN      6.0
7  TC      NaN     35.0
8  FD      NaN     46.0

In [25]:
dframe5=DataFrame({'key':['A','B','C','D','E','F'],'key2':['g','h','i','j','k','r'],'dframe5':[1,2,3,4,5,6]})
dframe5

key key2  dframe5
0   A    g        1
1   B    h        2
2   C    i        3
3   D    j        4
4   E    k        5
5   F    r        6

In [26]:



dframe6=DataFrame({'key':['F','B','Y','D','E','F'],'key2':['n','m','i','p','k','s'],'dframe6':[1,2,3,5,7,11]})
dframe6

key key2  dframe6
0   F    n        1
1   B    m        2
2   Y    i        3
3   D    p        5
4   E    k        7
5   F    s       11

In [31]:
pd.merge(dframe5,dframe6,on=['key','key2'],how='outer')

key key2  dframe5  dframe6
0    A    g      1.0      NaN
1    B    h      2.0      NaN
2    C    i      3.0      NaN
3    D    j      4.0      NaN
4    E    k      5.0      7.0
5    F    r      6.0      NaN
6    F    n      NaN      1.0
7    B    m      NaN      2.0
8    Y    i      NaN      3.0
9    D    p      NaN      5.0
10   F    s      NaN     11.0

# MERGE with index

In [35]:
dframe11=DataFrame({'key':['A','B','S','D','F'],'dval':[1,2,3,55,6]})

In [36]:
dframe11

key  dval
0   A     1
1   B     2
2   S     3
3   D    55
4   F     6

In [37]:
dframe12=DataFrame({'key':['G','P']},index=['A','S'])
                   

In [38]:
dframe12

key
A   G
S   P

In [44]:
pd.merge(dframe11,dframe12,left_on='key',right_index=True)

key key_x  dval key_y
0   A     A     1     G
2   S     S     3     P

In [45]:
pd.merge(dframe11,dframe12,left_on='key',right_index=True,how='outer')

key key_x  dval key_y
0   A     A     1     G
1   B     B     2   NaN
2   S     S     3     P
3   D     D    55   NaN
4   F     F     6   NaN

In [46]:
df_left_hr = DataFrame({'key1': ['SF','SF','SF','LA','LA'],
                   'key2': [10, 20, 30, 20, 30],
                   'data_set': np.arange(5.)})
df_right_hr = DataFrame(np.arange(10).reshape((5, 2)),
                   index=[['LA','LA','SF','SF','SF'],
                          [20, 10, 10, 10, 20]],
                   columns=['col_1', 'col_2'])

In [48]:
df_left_hr

key1  key2  data_set
0   SF    10       0.0
1   SF    20       1.0
2   SF    30       2.0
3   LA    20       3.0
4   LA    30       4.0

In [49]:
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [50]:
pd.merge(df_left_hr, df_right_hr, left_on=['key1','key2'],right_index=True)

key1  key2  data_set  col_1  col_2
0   SF    10       0.0      4      5
0   SF    10       0.0      6      7
1   SF    20       1.0      8      9
3   LA    20       3.0      0      1

In [59]:
df_left = DataFrame({'key': ['X','Y','Z','X','Y'],
                     'data': range(5)})
df_right = DataFrame({'group_data': [10, 20]}, index=['X', 'Y'])

In [60]:
df_left.join(df_right)


key  data  group_data
0   X     0         NaN
1   Y     1         NaN
2   Z     2         NaN
3   X     3         NaN
4   Y     4         NaN

In [61]:
df_left

key  data
0   X     0
1   Y     1
2   Z     2
3   X     3
4   Y     4

In [62]:
df_right

group_data
X          10
Y          20

In [66]:
pd.merge(df_left,df_right,left_on='key',right_index=True,how='outer')

key  data  group_data
0   X     0        10.0
3   X     3        10.0
1   Y     1        20.0
4   Y     4        20.0
2   Z     2         NaN

# CONCATENATE

In [3]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [8]:
arr2=np.random.randn(9).reshape(3,3)
arr2

array([[ 0.05778897,  0.62831457, -0.36874055],
       [-2.38185908,  2.23632747,  0.13527601],
       [-0.47801005,  1.25780296, -1.6054452 ]])

In [9]:
np.concatenate([arr1,arr2],axis=0)

array([[ 0.        ,  1.        ,  2.        ],
       [ 3.        ,  4.        ,  5.        ],
       [ 6.        ,  7.        ,  8.        ],
       [ 0.05778897,  0.62831457, -0.36874055],
       [-2.38185908,  2.23632747,  0.13527601],
       [-0.47801005,  1.25780296, -1.6054452 ]])

In [33]:
ser1=Series([0,1,2,3,4],index=['A','B','C','D','F'])
ser1

A    0
B    1
C    2
D    3
F    4
dtype: int64

In [32]:
ser2=Series([5,6,7,8,9],index=['E','B','C','D','F'])
ser2

E    5
B    6
C    7
D    8
F    9
dtype: int64

In [38]:
pd.concat([ser1,ser2],axis=0,sort=False,keys=[1,2])

1  A    0
   B    1
   C    2
   D    3
   F    4
2  E    5
   B    6
   C    7
   D    8
   F    9
dtype: int64

In [40]:
pd.concat([ser1,ser2],axis=1,sort=True,keys=[1,2])

1    2
A  0.0  NaN
B  1.0  6.0
C  2.0  7.0
D  3.0  8.0
E  NaN  5.0
F  4.0  9.0

In [41]:

dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [42]:
dframe1

X         Y         Z
0 -0.704437 -0.233991 -0.050260
1  0.887079  0.257997 -0.837936
2 -0.972362  1.352713  1.467031
3 -0.180254  0.302013  0.357565

In [43]:
dframe2

Y         Q         X
0 -1.298148  0.922324 -0.947035
1  1.556263  0.282020  0.195535
2  0.468175  0.834764 -1.598077

In [44]:
pd.concat([dframe1,dframe2])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN -0.704437 -0.233991 -0.050260
1       NaN  0.887079  0.257997 -0.837936
2       NaN -0.972362  1.352713  1.467031
3       NaN -0.180254  0.302013  0.357565
0  0.922324 -0.947035 -1.298148       NaN
1  0.282020  0.195535  1.556263       NaN
2  0.834764 -1.598077  0.468175       NaN

In [46]:
pd.concat([dframe1,dframe2],ignore_index=True,sort=True)

Q         X         Y         Z
0       NaN -0.704437 -0.233991 -0.050260
1       NaN  0.887079  0.257997 -0.837936
2       NaN -0.972362  1.352713  1.467031
3       NaN -0.180254  0.302013  0.357565
4  0.922324 -0.947035 -1.298148       NaN
5  0.282020  0.195535  1.556263       NaN
6  0.834764 -1.598077  0.468175       NaN

# combining data frames

In [4]:
#First Series
ser1 = Series([2,np.nan,4,np.nan,6,np.nan],
           index=['Q','R','S','T','U','V'])

#Second Series (based off length of ser1)
ser2 = Series(np.arange(len(ser1), dtype=np.float64),
           index=['Q','R','S','T','U','V'])

In [5]:
ser1


Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [51]:
ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [6]:
ser1.combine_first(ser2)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [7]:
r=np.nan
dframe11=DataFrame({'X':[1,r,3],
                   'Y':[5,r,r],
                   'Z':[9,r,r]})

In [54]:
dframe22=DataFrame({'X':[r,1,3],
                   'Y':[5,6,r],
                   'A':[8,9,69]})

In [55]:
dframe11

X    Y    Z
0  1.0  5.0  9.0
1  NaN  NaN  NaN
2  3.0  NaN  NaN

In [56]:
dframe22

X    Y   A
0  NaN  5.0   8
1  1.0  6.0   9
2  3.0  NaN  69

In [61]:
dframe11.combine_first(dframe22)

A    X    Y    Z
0   8.0  1.0  5.0  9.0
1   9.0  1.0  6.0  NaN
2  69.0  3.0  NaN  NaN


# RE-SHAPING

In [63]:
df1=DataFrame(np.arange(8).reshape(2,4),index=['la','sf'],columns=[1,2,3,4])

In [64]:
df1

1  2  3  4
la  0  1  2  3
sf  4  5  6  7

In [70]:
st=df1.stack()#make it a series
st

la  1    0
    2    1
    3    2
    4    3
sf  1    4
    2    5
    3    6
    4    7
dtype: int32

In [69]:
st.unstack()#make it again a dataframe

1  2  3  4
la  0  1  2  3
sf  4  5  6  7

# pivoting

In [71]:
# Lets create some data to play with:

# Note: It is not necessary to understand how this dataset was made to understand this Lecture.

#import pandas testing utility
import pandas.util.testing as tm; tm.N = 3

#Create a unpivoted function
def unpivot(frame):
    N, K = frame.shape
    
    data = {'value' : frame.values.ravel('F'),
            'variable' : np.asarray(frame.columns).repeat(N),
            'date' : np.tile(np.asarray(frame.index), K)}
    
    # Return the DataFrame
    return DataFrame(data, columns=['date', 'variable', 'value'])

#Set the DataFrame we'll be using
dframe = unpivot(tm.makeTimeDataFrame())
tm.makeTimeDataFrame()

A         B         C         D
2000-01-03  1.067666  0.834717  0.458839 -0.102718
2000-01-04  0.463135 -1.148459 -0.767812 -0.013982
2000-01-05 -0.418325  0.319871  1.007360 -0.027188

In [72]:
dframe

date variable     value
0  2000-01-03        A  0.882839
1  2000-01-04        A -0.117814
2  2000-01-05        A  1.626422
3  2000-01-03        B  0.723490
4  2000-01-04        B -0.833908
5  2000-01-05        B  1.069114
6  2000-01-03        C -0.744318
7  2000-01-04        C -0.246885
8  2000-01-05        C  0.846112
9  2000-01-03        D -0.131570
10 2000-01-04        D -0.571788
11 2000-01-05        D  0.346288

In [75]:
dframe.pivot('date','variable','value')

variable           A         B         C         D
date                                              
2000-01-03  0.882839  0.723490 -0.744318 -0.131570
2000-01-04 -0.117814 -0.833908 -0.246885 -0.571788
2000-01-05  1.626422  1.069114  0.846112  0.346288

# delete duplicates

In [76]:
dframe = DataFrame({'key1': ['A'] * 2 + ['B'] * 3,
                  'key2': [2, 2, 2, 3, 3]})
dframe

key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [77]:
dframe.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [78]:
dframe.drop_duplicates()

key1  key2
0    A     2
2    B     2
3    B     3

In [79]:
dframe.drop_duplicates('key1')

key1  key2
0    A     2
2    B     2

In [81]:
dframe.drop_duplicates('key1',keep='last')

key1  key2
1    A     2
4    B     3

# mapping

In [2]:
dframe=DataFrame({'city':['ddn','deoghar','delhi','noida','ranchi'],'state':['uttrak','jharkhand','delhi','up','jhar']})

In [3]:
dframe

city      state
0      ddn     uttrak
1  deoghar  jharkhand
2    delhi      delhi
3    noida         up
4   ranchi       jhar

In [4]:
col_map={'uttrak':'first','jharkhand':'second','delhi':'third','up':'forth','jhar':'fifth'}

In [7]:
dframe['order']=dframe['state'].map(col_map)

In [8]:
dframe

city      state   order
0      ddn     uttrak   first
1  deoghar  jharkhand  second
2    delhi      delhi   third
3    noida         up   forth
4   ranchi       jhar   fifth

# replace

In [9]:
ser=Series((1,2,3,5,6,5,6,np.nan,4,2,5,))

In [10]:
ser

0     1.0
1     2.0
2     3.0
3     5.0
4     6.0
5     5.0
6     6.0
7     NaN
8     4.0
9     2.0
10    5.0
dtype: float64

In [13]:
ser.replace([1,5],[111,555])

0     111.0
1       2.0
2       3.0
3     555.0
4       6.0
5     555.0
6       6.0
7       NaN
8       4.0
9       2.0
10    555.0
dtype: float64

In [14]:
ser.replace({6:6666})

0        1.0
1        2.0
2        3.0
3        5.0
4     6666.0
5        5.0
6     6666.0
7        NaN
8        4.0
9        2.0
10       5.0
dtype: float64

# rename index

In [39]:
dframe1= DataFrame(np.arange(12).reshape((3, 4)),
                 index=['NY', 'LA', 'SF'],
                 columns=['A', 'B', 'C', 'D'])
dframe1

A  B   C   D
NY  0  1   2   3
LA  4  5   6   7
SF  8  9  10  11

In [40]:

dframe1.rename(index={'NY':'NEW YORK'},
             columns={'A':'ALPHA','B':'boy'},inplace=True)

In [41]:
dframe1.index.map({'LA':'las'})

Index([nan, 'las', nan], dtype='object')

In [42]:
dframe1

ALPHA  boy   C   D
NEW YORK      0    1   2   3
LA            4    5   6   7
SF            8    9  10  11

# binning

In [8]:
years = [1990,1991,1992,2008,2012,2015,1987,1969,2013,2008,1999]

In [9]:
decade_bins = [1960,1970,1980,1990,2000,2010,2020]

In [10]:
decade_catogory = pd.cut(years,decade_bins)

In [11]:
decade_catogory

[(1980, 1990], (1990, 2000], (1990, 2000], (2000, 2010], (2010, 2020], ..., (1980, 1990], (1960, 1970], (2010, 2020], (2000, 2010], (1990, 2000]]
Length: 11
Categories (6, interval[int64]): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [49]:
decade_catogory.categories

IntervalIndex([(1960, 1970], (1970, 1980], (1980, 1990], (1990, 2000], (2000, 2010], (2010, 2020]],
              closed='right',
              dtype='interval[int64]')

In [51]:
pd.value_counts(decade_catogory)

(2010, 2020]    3
(1990, 2000]    3
(2000, 2010]    2
(1980, 1990]    2
(1960, 1970]    1
(1970, 1980]    0
dtype: int64

In [52]:
pd.cut(years,2,precision=1)

[(1969.0, 1992.0], (1969.0, 1992.0], (1969.0, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], ..., (1969.0, 1992.0], (1969.0, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], (1992.0, 2015.0]]
Length: 11
Categories (2, interval[float64]): [(1969.0, 1992.0] < (1992.0, 2015.0]]